version: '3.1'
networks:
  backend:
    external: true
services:
  mem_nginx:
    image:  registry.tuoitre.vn/services/service-token-nginx:v1
    container_name: token_nginx5
    hostname: token_nginx5
    volumes:
      - '.:/var/www/html/verify-token'
      - './docker/nginx/conf.d/nginx.conf:/etc/nginx/conf.d/nginx.conf'
      - './docker/nginx/logs:/var/log/nginx'
    ports:
      - 80:80
    network_mode: "backend"
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - 192.168.161.139
    depends_on:
      - mem_php80


  mem_php80:
    image:  registry.tuoitre.vn/services/service-token-php:v3
    build: ./docker/php80/php-fpm
    container_name: token_php805
    working_dir: /var/www/html
    volumes:
      - '.:/var/www/html/verify-token'
      - './docker/php80/supervisor/conf.d:/etc/supervisor/conf.d'
      - './docker/php80/supervisor/logs:/var/log/cache'
      - './docker/php80/php-fpm/conf.d/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini'
    expose:
      - 9000
    ports:
      - 9000:9000
    network_mode: "backend"
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - 192.168.161.139

    depends_on:

      - mem_elasticsearch77

  mem_elasticsearch77:
    image: registry.tuoitre.vn/services/service-token-elasticsearch:v3
    build: ./docker/elasticsearch717
    container_name: mem_elasticsearch5
    volumes:
      - ./docker/elasticsearch717/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    #      - ELASTICSEARCH_HEAP_SIZE=1g
    #        expose:
    #            - '9200:9200'
    ports:
      - 9200:9200
      - 9300:9300
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - 192.168.161.139
    network_mode: "backend"
  mem_redis:
    image: registry.tuoitre.vn/services/token_redis:v1
    container_name: mem_redis162
    volumes:
      - './docker/redis/data:/data'
    ports:
      - 6379:6379
    dns:
      - 8.8.8.8
      - 4.4.4.4
      - 192.168.161.139
    network_mode: "backend"
  memcached:
    image: registry.tuoitre.vn/services/token_memcached:v1
    container_name: token_memcached4

    ports:
      - "11211:11211"
    network_mode: "backend"
