<?php


use Illuminate\Foundation\Console\Kernel as ConsoleKernel;

class Kernel extends ConsoleKernel
{
    public function bootstrappers()
    {
        $bootstrappers = parent::bootstrappers(); // TODO: Change the autogenerated stub

        if ($key = array_search(\Illuminate\Foundation\Bootstrap\LoadConfiguration::class, $bootstrappers) !== false) {
            $bootstrappers[$key] = \Common\Bootstrap\LoadConfiguration::class;
        }
        return $bootstrappers;
    }
}
