<?php

namespace TuoiTre\SSO\Exceptions;

use Exception;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Throwable;
use TuoiTre\SSO\Constants\ResponseTypeConstant;

class ApiHandler extends BaseApiHandler
{
    public function render($request, Throwable $e)
    {
        if (str_starts_with(
                $request->url(),
                $request->getSchemeAndHttpHost() . '/'
                . (!empty($urlPrefix = config('laravel-sso.urlPrefix')) ? $urlPrefix . '/' : '')
                . (!empty($version = config('laravel-sso.version')) ? $version . '/' : '')
            ) !== false) {
            if ($e instanceof HttpException) {
                return response()->json(
                    [
                        'message' => $e->getMessage(),
                        'code' => $e->getStatusCode(),
                        'type' => ResponseTypeConstant::TYPE_ERROR_OTHER
                    ],
                    $e->getStatusCode()
                );
            }

            if ($e instanceof Exception) {
                return response()->json(
                    [
                        'message' => __('sso::messages.otherError'),
                        'code' => Response::HTTP_INTERNAL_SERVER_ERROR,
                        'type' => ResponseTypeConstant::TYPE_ERROR_OTHER
                    ],
                    Response::HTTP_INTERNAL_SERVER_ERROR
                );
            }
        }

        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
