<?php

namespace TuoiTre\SSO\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Str;

class Broker extends Model
{

    public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static::saving(function ($model) {
            if (is_null($model->secret_key)) {
                $model->secret_key = Str::random(64);
            }
            if (is_null($model->public_key)) {
                $model->public_key = Str::random(48);
            }
        });
    }

    const STATUS_ACTIVE = 1;
    const STATUS_DISABLE = 2;

    protected $table = 'brokers';

    protected $fillable = [
        'name',
        'status',
        'domain',
        'public_key',
        'secret_key'
    ];


    protected $attributes = [
        'status' => self::STATUS_ACTIVE
    ];

    public $timestamps = ['created_at', 'updated_at'];
}
