<?php

/**
 * Created by Reliese Model.
 */

namespace Common\App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class MemMember
 *
 * @property int $id
 * @property string $username
 * @property string $guid
 * @property string|null $phone
 * @property string|null $email
 * @property string|null $password_hash



 *
 * @package App\Models
 */
class Account extends Model
{
    public $table = 'account';


    protected $fillable = [
        'guid',
        'username',
        'phone',
        'password_hash',
        'privateKey',
        'email',

    ];
    public function getTable()
    {
        return parent::getTable(); // TODO: Change the autogenerated stub
    }

}
