<?php

/**
 * Created by Reliese Model.
 */

namespace Common\App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class EndPoint
 *
 * @property int $id
 *  @property string $name
 * @property string $publicKey
 * @property string|null $privateKey
 * @property string|null $serveIp
 * @property string|null $domain
 * @property int|null $expire
 * @property int|null $status
 * @property int|null $tracker
 * @property string|null $idServices


 *
 * @package App\Models
 */
class EndPoint extends Model
{
    public $table = 'end_point';


    protected $fillable = [
        'name',
        'serveIp',
        'domain',
        'publicKey',
        'expire',
        'tracker',
        'status',
        'privateKey',
        'idServices',

    ];
    public function getTable()
    {
        return parent::getTable(); // TODO: Change the autogenerated stub
    }

}
