<?php

/**
 * Created by Reliese Model.
 */

namespace Common\App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Role
 *
 * @property int $id
 * @property string $action
 * @property array $route
 * @property string|null $status



 *
 * @package App\Models
 */
class Permission extends Model
{
    public $table = 'permission';


    protected $fillable = [

        'action',
        'route',
        'status'

    ];
    public function getTable()
    {
        return parent::getTable(); // TODO: Change the autogenerated stub
    }

}
