<?php

/**
 * Created by Reliese Model.
 */

namespace Common\App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Model;

/**
 * Class Role
 *
 * @property int $id
 * @property string $name
 * @property array $id_permission
 * @property array|null $name_permission
 * @property string|null $status




 *
 * @package App\Models
 */
class Role extends Model
{
    public $table = 'role';


    protected $fillable = [

        'name',
        'id_permission',
        'name_permission',
        'status'

    ];
    public function getTable()
    {
        return parent::getTable(); // TODO: Change the autogenerated stub
    }

}
