<?php

namespace Common\App\Http;

use Illuminate\Foundation\Http\Kernel as HttpKernel;

class Kernel extends HttpKernel
{
    public function bootstrappers()
    {
        $bootstrappers = parent::bootstrappers(); // TODO: Change the autogenerated stub

        if ($key = array_search(\Illuminate\Foundation\Bootstrap\LoadConfiguration::class, $bootstrappers) !== false) {
            $bootstrappers[$key] = \Common\Bootstrap\LoadConfiguration::class;
        }
        return $bootstrappers;
    }
}
