<?php

namespace App\Exceptions;

use App\Constants\BaseResponseTypeConstant;
use Illuminate\Foundation\Exceptions\Handler as ExceptionHandler;
use Symfony\Component\HttpKernel\Exception\HttpException;
use Throwable;

class Handler extends ExceptionHandler
{
    /**
     * A list of the exception types that are not reported.
     *
     * @var array<int, class-string<Throwable>>
     */
    protected $dontReport = [
        //
    ];

    /**
     * A list of the inputs that are never flashed for validation exceptions.
     *
     * @var array<int, string>
     */
    protected $dontFlash = [
        'current_password',
        'password',
        'password_confirmation',
    ];

    /**
     * Register the exception handling callbacks for the application.
     *
     * @return void
     */
    public function register()
    {
        $this->reportable(function (Throwable $e) {
            if (app()->bound('sentry')) {
                app('sentry')->captureException(
                    $e,
                    \Sentry\EventHint::fromArray(['extra' => ['time' => date('Y-m-d h:i:s')]])
                );
            }
        });
    }

    public function render($request, Throwable $e)
    {
        if ($e instanceof HttpException) {
            $statusCode = (int)$e->getStatusCode();

            if (empty($e->getMessage())) {
                $msg = match ($statusCode) {
                    401, 403 => 'You are not authorized to view the requested resource.',
                    404 => 'The page you requested does not exist.',
                    default => 'An error may have occurred.'
                };
            } else {
                $msg = $e->getMessage();
            }
//            if ($request->expectsJson()
//                || str_starts_with(
//                    $request->url(),
//                    $request->getSchemeAndHttpHost() . '/' . env('APP_API_PREFIX', 'api/front')
//                ) !== false
//            ) {
//                return response()->json([
//                    'success' => false,
//                    'code' => $statusCode,
//                    'message' => "Đã xảy ra lỗi",
//                    'type' => !empty($e->getCode()) ? $e->getCode() : $this->getTypeByStatus($statusCode),
//                    'error' => $msg
//                ], $statusCode);
//            }

//            return response()->view('error', ['code' => $statusCode, 'message' => $msg]);
        }
        return parent::render($request, $e); // TODO: Change the autogenerated stub
    }

    private function getTypeByStatus(int $status): string
    {
        return match ($status) {
            401 => BaseResponseTypeConstant::RESPONSE_TYPE_ERROR_UNAUTHENTICATED,
            403 => BaseResponseTypeConstant::RESPONSE_TYPE_ERROR_FORBIDDEN,
            404 => BaseResponseTypeConstant::RESPONSE_TYPE_ERROR_NOT_FOUND,
            default => BaseResponseTypeConstant::RESPONSE_TYPE_ERROR_OTHER,
        };
    }
}
